filters:
  httpServer:
    port: 8081
  envoy:
    uri: public.ecr.aws/k9v9d5v2/sentryflow-httpfilter
    gatewayTag: "latest-gateway"

receivers:
  serviceMeshes:
    - name: istio-gateway
      namespace: istio-system

exporter:
  grpc:
    port: 8080
