filters:
  httpServer:
    port: 8081
  envoy:
    uri: public.ecr.aws/k9v9d5v2/sentryflow-httpfilter
    gatewayWithRatelimitTag: "latest-gateway-ratelimit"

receivers:
  serviceMeshes:
    - name: istio-gateway
      namespace: istio-system
      ratelimiting: 
        enabled: true

exporter:
  grpc:
    port: 8080
