# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Authors of SentryFlow

filters:
  envoy:
    uri: public.ecr.aws/k9v9d5v2/sentryflow-httpfilter
    gatewayTag: "latest-gateway"
    sidecarTag: "latest-sidecar"

receivers: # aka sources
  serviceMeshes:
    - name: istio-sidecar
      namespace: istio-system
exporter:
  grpc:
