# Default values for SentryFlow.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: public.ecr.aws/k9v9d5v2/sentryflow
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
# Arguments to pass SentryFlow container
args:
  - --config
  - /var/lib/sentryflow/config.yaml
  # Uncomment the following to turn on debug mode
#  - --development
#  - "true"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
genericLabels:
  app.kubernetes.io/part-of: sentryflow
podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  ports:
    - name: exporter
      port: 8080 # Make sure to use the same port as `.exporter.grpc.port` field of `config`
      targetPort: 8080 # Make sure to use the same port as `.filters.server.port` field of `config`
      nodePort: 30880
      protocol: TCP
    - name: http-receiver
      port: 8081 # Make sure to use the same port as `.filters.server.port` field of `config`
      targetPort: 8081 # Make sure to use the same port as `.filters.server.port` field of `config`
      nodePort: 30001
      protocol: TCP
    - name: tcp-receiver
      port: 5000 
      targetPort: 5000 
      nodePort: 30002
      protocol: TCP
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi
# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /healthz
    port: receiver
    httpHeaders:
      - name: status
        value: "200"
readinessProbe:
  httpGet:
    path: /healthz
    port: receiver
    httpHeaders:
      - name: status
        value: "200"
# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
# Traffic sources configuration
config:
  serverPort: 8081
  tcpServerPort: 5000
  grpcPort: 8080

  receivers:
    nginxIngressController:
      enabled: false
      deploymentName: ""
      configMapName: ""
      sentryFlowNjsConfigMapName: "sentryflow-nginx-inc"
      namespace: ""

    istio:
      enabled: false
      sidecar: 
        enabled: false
        tag: "latest-sidecar"
      gateway: 
        enabled: true
        tag: "latest-gateway"
        ratelimiting: 
          enabled: true
          tag: "latest-gateway-ratelimit"
      namespace: "istio-system"
      envoyFilterUri: "public.ecr.aws/k9v9d5v2/sentryflow-httpfilter"

    azureApim:
      enabled: false

    awsApigw:
      enabled: false

    f5BigIp:
      enabled: false

    kongGateway:
      enabled: false
      deploymentName: "kong-kong"
      namespace: "kong"
      plugin:
        httpEndpoint: "http://sentryflow.sentryflow:8081/api/v1/events"
        timeout: 10000
        keepalive: 60000
  httpExporter:
    enabled: false
    timeoutSeconds: 5
    webhook:
      name: ""
      url: ""
      method: "POST"
      headers: {}
      tls:
        caCertPath: ""
        clientCertPath: ""
        clientKeyPath: ""
        insecureSkipVerify: false
            
volumes:
  - name: sentryflow
    configMap:
      name: sentryflow
      defaultMode: 420
volumeMounts:
  - name: sentryflow
    mountPath: "/var/lib/sentryflow/"
    readOnly: true

