# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of SentryFlow

name: Latest release
on:
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: Find out which files were changed
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      sentryflow: ${{ steps.filter.outputs.sentryflow}}
      envoyfilter: ${{ steps.filter.outputs.envoyfilter}}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            sentryflow:
              - 'sentryflow/**'
            envoyfilter:
              - 'filter/envoy/envoy-wasm-filters/**'

  release-sentryflow-image:
    needs: [ files-changed ]
    if: ${{ github.repository == 'accuknox/sentryflow' && needs.files-changed.outputs.sentryflow == 'true' }}
    name: Build and push sentryflow's image
    uses: ./.github/workflows/release-image.yaml
    with:
      WORKING_DIRECTORY: ./sentryflow
      NAME: sentryflow
    secrets: inherit

  # release-envoy-filter-image:
  #   needs: [ files-changed ]
  #   if: ${{ github.repository == 'accuknox/sentryflow' && needs.files-changed.outputs.envoyfilter == 'true' }}
  #   name: Build and push envoyfilter's image
  #   uses: ./.github/workflows/release-image.yaml
  #   with:
  #     WORKING_DIRECTORY: ./filter/envoy/envoy-wasm-filters
  #     NAME: sentryflow-httpfilter
  #   secrets: inherit

  release-envoy-filter-sidecar-image:
    needs: [ files-changed ]
    if: ${{ github.repository == 'accuknox/sentryflow' && needs.files-changed.outputs.envoyfilter == 'true' }}
    name: Build and push envoyfilter sidecar latest image
    uses: ./.github/workflows/wasm-push-image/action.yaml@main
    with:
      DOCKER_CONTEXT: filter/envoy/envoy-wasm-filters
      DOCKERFILE: filter/envoy/envoy-wasm-filters/Dockerfile
      IMAGE_NAME: sentryflow-httpfilter
      IMAGE_TAG: 'latest-sidecar'
      DOCKER_BUILD_ARGS: PLUGIN_TYPE=sidecar
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ID }}

  release-envoy-filter-gateway-image:
    needs: [ files-changed ]
    if: ${{ github.repository == 'accuknox/sentryflow' && needs.files-changed.outputs.envoyfilter == 'true' }}
    name: Build and push envoyfilter gateway latest image
    uses: ./.github/actions/wasm-push-image/action.yaml@main
    with:
      DOCKER_CONTEXT: filter/envoy/envoy-wasm-filters
      DOCKERFILE: filter/envoy/envoy-wasm-filters/Dockerfile
      IMAGE_NAME: sentryflow-httpfilter
      IMAGE_TAG: 'latest-gateway'
      DOCKER_BUILD_ARGS: PLUGIN_TYPE=gateway
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ID }}
